Endpoints eliminar y modificar alerta
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #10
Opened 2024-04-09 05:26 UTC by MoyBadillo117

Endpoints

2024-04-09 17:37 UTC, Aram32mm requested changes
Buen Código Moy, se que no te toca pero creo que necesitaremos un patch, lo podrias hacer ?

2024-04-09 17:51 UTC, AntonioLaurance reviewed
Buenos endpoints Moi, están completamente funcionales y bien documentados, mis únicas sugerencias son relacionadas con el tipo de datos de retorno de cada uno de tus endpoints y con los código HTTP.

2024-04-09 17:51 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/AlertController.java
Buen trabajo Moisés, he aquí algunas de mis observaciones:
- La petición ```DELETE /api/alerts/{alertId}``` no retorna el código HTTP 204 (No Content) sino que retorna el código 200 (OK), en este caso sugiero que el endpoint no retorne ningún texto ya que se podría decir que cuando retorna el código 204 la alerta se borró exitosamente.
- Generalmente cuando se utiliza el verbo **PUT** de **HTTP** en alguna API se envía parte del JSON o el JSON entero y este como retorna como respuesta un JSON de como quedaría el campo a modificar, en el endpoint de ```PUT /api/alerts/{alertId}``` recomendaría que la función **putAlert(@PathVariable(name = "alertId") long id)** también tome un **AlertDTO** como argumento que es el JSON que se le va a pasar de como queremos que quede el registro con el Id especificado, además de que este endpoint retorne un JSON de **Alert**.

Fuera de estas dos observaciones considero todo bien dentro de tu código, buena documentación!!

2024-04-09 17:57 UTC, AntonioLaurance commented
Creo que aquí se podríamos necesitar el verbo ```PUT``` ya que la modificación impacta sobre la totalidad del registro y creo que ```PATCH``` se utiliza para actualizar partes del registro, en resumen se podría decir que uno cambia la totalidad de los datos del registro (```PUT```) y otro solo parcialmente (```PATCH```).

¿Qué opinan @Aram32mm, @MoyBadillo117 y @abeejita que es mejor usar en la API de actualización de alertas ```PATHCH``` o ```PUT```?

2024-04-09 19:51 UTC, abeejita commented
@AntonioLaurance @AntonioLaurance para la función del endpoint de Moy PUT está bien. El PATCH aún así lo podríamos poner adicionalmente.

2024-04-10 00:25 UTC, AntonioLaurance approved these changes
Hasta ahora todo el código bien, todo funcional y las clases bien definidas con nombres coherentes para el miércoles, en el futuro sugiero hacer lo de los comentarios anteriores pero por ahora todo bien. Excelente trabajo Moi 😃!!

2024-04-21 19:23 UTC, Aram32mm requested changes
todo lo que dio Richie, matchear los codigos de respuesta y el put recibe un dto, cambias todo el recurso por otro. Si fuera patch recibe un map. Lo recibe en el body

2024-04-24 11:24 UTC, AntonioLaurance requested changes
Buenos cambios Moi!!, mi únicas notas aquí serían cambiar el código de respuesta en tu **API** de ```DELETE``` y sobre tomar el **ID** de la **url** en la de ```PUT```.

2024-04-24 11:24 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/AlertController.java
> +        return ResponseEntity.ok("");
Muy buenos cambios Moisés Badillo (@MoyBadillo117), mis únicas sugerencias aquí son: 
- [ ] Veo que ya se cambió la documentación de los códigos de respuesta **HTTP** en **Swagger**, se pusó el ```200 (OK)``` en lugar del ```204 (No Content)``` (**linea 68** de tu código), en ese caso sugiero volver a poner el código de respuesta **HTTP** ```204 (No Content)``` ya que la API ```DELETE /api/alerts/{alertId}``` debería retornar ese código de respuesta **204**.
- [ ] El código de respuesta **HTTP** que retorna la API de ```DELETE /api/alerts/{alertId}``` sigue siendo ```200 (OK)``` en lugar de ```204 (No Content)```, para esto sugiero cambiar la **línea  73** de código por ```return new ResponseEntity.noContent().build()``` en lugar de ```return new ResponseEntity<>(alertDTO, HttpStatus.OK);```.
- [ ] En la API de ```PUT /api/alerts/{alertId}``` sugiero poner como variable que se le pasa a la función de ```putAlert(@RequestBody AlertDTO alertDTO)```  la de ```@PathVariable(name = "alertId") long id``` ya que actualmente la función que corresponde a esta API solamente toma el JSON nuevo pero no toma el **ID** de la **url** y por lo tanto no se puede saber que registro de la base de datos modificar.

De allí en fuera todo bien con este código.

2024-04-24 23:55 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/resources/application.properties
Las credenciales MySQL ya no están expuestas.

2024-04-25 00:08 UTC, AntonioLaurance approved these changes
¡Excelente código Moises Badillo (@MoyBadillo117)!

2024-04-25 19:14 UTC, AntonioLaurance commented
No actualizado.

2024-04-26 03:21 UTC, closed without merging