api/users PATCH (change relevant data)
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #102
Opened 2024-04-30 03:34 UTC by A01662420

- Solo se actualizan los datos relevantes (firstName y lastName), excluyendo el nombre de usuario (username), el correo electrónico (email) y la contraseña (password).

- No se devuelven datos sensibles como la contraseña en la respuesta, ya que en el UserInfoDTO no lo agregué.

- Por ultimo se devuelve una instancia de UserInfoDTO en lugar de UserDTO como me había mencionado aram.

2024-04-30 03:56 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
> +    @PatchMapping ("/{id}/change relevant info")
evitar espacios en el path para el endpoint

2024-04-30 03:57 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
> +
@Aram32mm mappers en vez de setters?

2024-04-30 03:58 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/User/UserInfoDTO.java
> -}
Documentar cada campo del DTO con @schema

2024-04-30 03:59 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/User/UserInfoDTO.java
>  package com.springboot.connectmate.dtos.User;
También, utiliza @data para que se te armen los getters y setters en vez de definirlos por tu cuenta.

2024-04-30 03:59 UTC, abeejita commented
Puedes adjuntar en tu PR un screenshot de tu endpoint funcionando en postman/restman/o el navegador por fis?

2024-04-30 04:00 UTC, abeejita requested changes
En general bien, solo hacer algunos cambios sugeridos :))

2024-04-30 15:54 UTC, Aram32mm requested changes
hmm, me extraña que hayas hecho todo de nuevo. Paso 1, docuemnta tu DTO. Paso 2 desde controller hasta serviceImpl donde veas UserDTO, solo cambialo por UserInfoDTO, la demas logica no deberias de moverla, todo esta bien

2024-04-30 15:54 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/User/UserInfoDTO.java
> -}
documentar con swagger y valores de ejemplo

2024-04-30 15:54 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/User/UserInfoDTO.java
>  package com.springboot.connectmate.dtos.User;
en efecto

2024-04-30 15:54 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
> +
si

2024-04-30 15:54 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
> +    @PatchMapping ("/{id}/change relevant info")
si

2024-04-30 20:29 UTC, A01662420 commented
oye @Aram32mm, me hice bolas, entonces ya no vamos a usar el userdto? y solo el userinfodto?, porque me dices que lo cambie en los demás pero no estoy captando.

2024-04-30 21:20 UTC, AntonioLaurance requested changes
¡Buen trabajo Gerry!, solamente algunas sugerencias para aprobar la **Pull Request** las cuales son: 
- [ ] Evitar espacios en el *path* del *endpoint*
- [ ] Poner ```{userId}``` en lugar de ```{id}``` en el decorador de la función del controlador y en sus parámetros, renombrar variables que tengan que ver con esto. 
- [ ] Hacer otro **DTO** para tu **API** especialmente uno como el que ya tienes pero que tenga el atributo de contraseña esto para el envío para modificar datos pero no para la recepción de contraseñas (para **DTO** de recepción el que tienes está bien pero para envío no).
- [ ] Corregir errores que impiden que corra tu código.
- [ ] Adjuntar capturas de pantalla de tu *endpoint* funcionando.

2024-04-30 21:20 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
> +    @PatchMapping ("/{id}/change relevant info")
Sugiero también poner ```{userId}``` en lugar de ```{id}``` en el decorador ```@PatchMapping```.

2024-04-30 21:20 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
> +
Falto importar **UserInfoDTO** para utilizarlo además de **ResourceNotFoundException**, además de que estoy de acuerdo con las sugerencias de Abi y de Aram.

2024-04-30 21:20 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
> +    @PatchMapping ("/{id}/change relevant info")
En ``` updateUserPartially(@PathVariable(name = "id") long id, @RequestBody UserInfoDTO UserInfoDTO)``` hay que considerar que el usuario podrá actualizar su contraseña a través de esta **API** por lo que sugiero un **DTO** diferente (que tenga contraseña) para enviar que para recibir datos (que no tenga contraseña).

2024-04-30 21:20 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/dtos/User/UserInfoDTO.java
> -}
Hacer otro **DTO** igual como el de **UserInfoDTO** pero que contenga además el atributo de contraseña.

2024-05-01 16:34 UTC, A01662420 commented
<img width="1396" alt="Captura de pantalla 2024-04-30 a la(s) 8 34 26 p m" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/94323087/05e233fe-aea2-4258-94d6-bdd52f33ba08">

Había olvidado adjuntar la pic

2024-05-01 17:17 UTC, Aram32mm requested changes
quitale todas los gettters y setters a los dto y usa @Data, la logica nunca va en controller, siempre en servicio. documenta dtos con swagger no solo sus propiedades.

2024-05-01 19:59 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
> +    public ResponseEntity<UserInfoDTO> updateUserPartially(@PathVariable(name = "userId") long id, @RequestBody UserInfoDTO userInfoDTO) {
En vez de un response entity, regresaría tal cual el userInfoDTO

2024-05-01 21:10 UTC, AntonioLaurance requested changes
Buen trabajo mi **Gerry**, mis sugerencias aquí es hacer el *endpoint* funcional ya que hay un error al llamar a la **API** que es este: 
<img width="1392" alt="Screenshot 2024-05-01 at 15 10 11" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/74690107/8f2286d6-6417-4832-b914-fb7eeab8296f">

Parece ser problemas con los *mappers* favor de corregirlo, quedo atento si llega a haber una duda.

2024-05-01 21:18 UTC, A01662420 commented
<img width="1075" alt="Captura de pantalla 2024-05-01 a la(s) 3 17 54 p m" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/94323087/797ff157-d335-4fca-a146-1bd52ad76ae5">

2024-05-01 21:22 UTC, A01662420 commented on src/main/java/com/springboot/connectmate/dtos/User/UpdateUserRequestDTO.java
ya corregí lo de los getters y setters

2024-05-01 21:23 UTC, A01662420 commented on src/main/java/com/springboot/connectmate/dtos/User/UpdateUserRequestDTO.java
y también justo le cambie el nombre porque creo que si había error ahí, (update-partially)

2024-05-01 23:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/dtos/User/UpdateUserRequestDTO.java
Veo que ya se acataron todas las sugerencias con este archivo, por lo que lo veo perfecto.

2024-05-01 23:35 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/dtos/User/UserInfoDTO.java
>  package com.springboot.connectmate.dtos.User;
Creo que ya se está utilizando el decorador ```@Data```, por lo que estos comentarios ya están resueltos.

2024-05-02 00:20 UTC, AntonioLaurance requested changes
¡Buen código **Gerry**!, estuve checando tu *endpoint* y funciona de maravilla (el **JSON** de envío y de retorno son diferentes por lo que se evita la exposición de las contraseñas), mis únicas sugerencias aquí son de estructura de funciones y sobre ponerte de acuerdo con **Aram** (@Aram32mm) sobre tu función en el controlador, de allí en fuera vi que implementaste los cambios que te comentábamos. 

Igual si tienes dudas no dudes en contactarnos. ¡Excelente trabajo **Luis Gerardo**, que siempre confunden conmigo, jaja!

2024-05-02 00:20 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/UserServiceImpl.java
> +        if (existingUser == null) {
Buen código el de los servicios de **User**, he aquí mis comentarios:
- [ ] Ese ```if``` se puede omitir entero ya que en la función de ```getUserById(id)``` ya está definido ese caso.
- [ ] Con las **líneas 74 y 75** estás obligando a que el usuario actualicé por lo menos el ```firstName``` y el ```lastName```, pienso que para todas las actualizaciones incluyendo para las del segundo ```if``` (que se podría omitir entero también) se podría hacer como en el método ```patchUser(long id, Map<String, Object> fields)``` que actualiza con ```switch case break``` dependiendo de los campos provistos a modificar. 

De allí en fuera veo todo bien con este código.

2024-05-02 00:53 UTC, Aram32mm approved these changes

2024-05-02 02:41 UTC, AntonioLaurance approved these changes
Ya veo algunas modificaciones en el *endpoint*, muy bueno este nuevo **JSON** que retorna, tengo unos comentarios sobre todo de estética para que sean abordados más adelante y tomados como referencias para las siguientes **Pull Request**.

¡Muchas felicidades **Gerry**!

2024-05-02 02:41 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/controllers/UserController.java
- [ ] Eliminar ```import``` no usado.

2024-05-02 03:04 UTC, abeejita approved these changes

2024-05-02 03:09 UTC, merged