Endpoints GET /api/insight and PUT DELETE /api/insight/{id} (17 & 18)
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #11
Opened 2024-04-09 05:43 UTC by AntonioLaurance

Endpoints JSON's and documentation with dummy data.

2024-04-09 17:44 UTC, Aram32mm requested changes
Hola Richie, excelente código, 2 cosas. Recuerda que hay 2 gitignores uno de git y otro nativo a SpringBoot(adentro del proyecto).  Pon lo de los ds stores dentro del gitognore nativo, ya que ahorita si pusheaste los binarios. Al final cómo quedo esto ? Suggestion, Action o Task? Sería Bueno Standarizar

2024-04-09 18:28 UTC, AntonioLaurance commented
Al final quedo como **Suggestion** en el código ya que cuando nos pusimos de acuerdo con el nombre de **Task** en el documento, me dió miedo cambiarlo y como ya había hecho una cantidad considerable de código había que cambiarlo en muchas localizaciones temiendo que cause algún error o algo así, pero pienso que puedo ahorita puedo cambiarlo a **Task** o a todo a **Suggestion** ya que creo que sería menos tardado y mi temor de romper algo disminuiría, ¿qué dicen @Aram32mm y @abeejita  por ahora le dejamos en **Suggestion** y ya después le cambiamos a **Task**?

2024-04-09 18:48 UTC, Aram32mm commented
SIN MIEDO AL EXITO RICHIE!!!! VAMOS CON TODO, HAY QUE HACER Y DESHACER EL CÓDIGO. Solo tienes que cambiar el nombre de las variables y cuando le cambias el nombre a los archivos, IntelliJ te refactoriza los imports, no te preocupes de ese lado

2024-04-09 18:49 UTC, Aram32mm commented
Igual cualquier problema que surga lo vemos juntos

2024-04-09 18:54 UTC, AntonioLaurance commented
Me gusta tu idea, me animaste, voy a cambiarles el nombre 😃 a los archivos y al código dentro de ellos para que quede **Task**!!

2024-04-09 19:32 UTC, AntonioLaurance commented
Muchas gracias Aram, ya está listo el cambio de nombres, allí lo podrías verificar y darme tus sugerencias por favor.

2024-04-10 00:15 UTC, Aram32mm approved these changes
Hola Richie, excelente código, 2 cosas. Recuerda que hay 2 gitignores uno de git y otro nativo a SpringBoot(adentro del proyecto).  Pon lo de los ds stores dentro del gitognore nativo, ya que ahorita si pusheaste los binarios. Al final cómo quedo esto ? Suggestion, Action o Task? Sería Bueno Standarizar

2024-04-16 06:03 UTC, AntonioLaurance commented
Muchas gracias @abeejita por los comentarios en clase acerca de mi código, ya está listo el cambio de nombres, el cambio de **Tasks** a **Insights** además de que se agregó más *dummy data* a la API de ```GET /api/insight```, ¿lo podrían revisar y darme sus sugerencias por favor?

2024-04-18 01:39 UTC, abeejita approved these changes
Todo bien richieee

2024-04-18 01:40 UTC, merged