tomaaaaa
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #112
Opened 2024-05-01 00:09 UTC by zzentenoo

2024-05-01 03:57 UTC, zzentenoo commented
Chavales les pido porfavor que mergeen lo que acabo de hacer, ya funciona plenamente
<img width="720" alt="Screenshot 2024-04-30 at 9 57 06 p m" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/66924428/f9665641-eb30-4a97-8b93-4cce595ad002">

2024-05-01 17:12 UTC, Aram32mm requested changes

2024-05-01 17:12 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/InsightController.java
port que no solo retornas RE<List<InsightDTO>>, que haces aqui ?

2024-05-02 00:23 UTC, Aram32mm approved these changes
bien padrino

2024-05-02 02:26 UTC, AntonioLaurance requested changes
¡Buen trabajo Fede!, ya probé tu *endpoint* y funciona bien además de que la documentación en **Swagger** está disponible para tu *endpoint*, mi única nota para aprobar esta **Pull Request** sería quitar los *imports* no usados en **InsightController**. 

De allí en fuera veo todo bien, con muy buena calidad.

2024-05-02 02:40 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/services/impl/InsightServiceImpl.java
> +    // TODO: FIX N+1 QUERY PROBLEM
luego te lo explico Richie, no te preocupes, aprueba el merge luego vemos eso

2024-05-02 02:50 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/InsightServiceImpl.java
> +    // TODO: FIX N+1 QUERY PROBLEM
De acuerdo Aram.

2024-05-02 02:51 UTC, AntonioLaurance approved these changes

2024-05-02 02:52 UTC, merged