Added alerts and AgentMetrics/id enddpoints and dtos
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #13
Opened 2024-04-10 05:33 UTC by zzentenoo

2024-04-10 06:02 UTC, abeejita commented
Hay conflictos con main ):

2024-04-10 17:32 UTC, AntonioLaurance approved these changes
Muy buen código Fede, anoté algunas sugerencias para después.

2024-04-10 17:32 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/dtos/AlertDTO.java
Como sugerencia para después sugiero definir los atributos de **type**, **status** y **severity** como **enum** en lugar de **String** ya que esto hace que esté autodocumentado el código y nos da ejemplos de los valores que pueden tomar estos campos además de que al pasarlo a JSON se convierte a **String** automáticamente, buena **DTO** para alertas y buena documentación de atributos.

2024-04-10 17:32 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/AlertController.java
Buenos datos y estructura del JSON.

2024-04-10 17:32 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/AgentController.java
Buen código para el *endpoint* de ```GET /api/agents/metrics/{id}```, he aquí algunas de mis observaciones:
- ```import java.util.Map``` es importada pero nunca usada en el archivo.
- En la función **getAgentMetricsById(@PathVariable(name = "id") long id)** el tipo de dato de **id** es el tipo nativo **long** y no **Long** como objeto, creo que podremos utilizar **Long** porque nos puede ofrecer más posibilidades al unirlo con la base de datos. 

Buena estructura del JSON con los datos *dummy*.

2024-04-16 06:15 UTC, AntonioLaurance commented
Nueva fecha de entrega: ```Lunes 22 de abril del 2024```
Favor de implementar las sugerencias indicadas en los comentarios.

2024-04-21 19:27 UTC, Aram32mm requested changes
no vamos a tener call metrics, checa el modelo de base de datos para armar los dtos

2024-04-24 11:57 UTC, AntonioLaurance requested changes
Muy buenos cambios Fede!!, mis notas aquí son arreglar algunas cosas que hacen que el código se ejecute, por ejemplo las dependencias del **enum** (nombre de los *imports* y nombre del tipo de datos), además de algunas sugerencias de notación y remover librerías.

De allí en fuera todo bien :).

2024-04-24 11:57 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/dtos/AlertDTO.java
Me gusta el cambio de nombre del **enum** de tipo ```severity``` a tipo ```AlertSeverity``` pero esto causa conflictos con otros archivos, especialmente con el **Setter** personalizado en la **línea 101** del archivo **AlertDTO.java** y con algunos datos *dummy* en **AlertController.java**, ¿podrías cambiar este **Setter** y resolver los conflictos con este último archivo por favor @zzentenoo?

2024-04-24 11:57 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/dtos/AgentMetricsDTO.java
Hay que remover la línea ```import java.util.Map``` ya que nunca es usada.

2024-04-24 11:57 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/AgentController.java
Buenos datos *dummy* en ```getAgentMetricsById(@PathVariable("id") Long id)``` mi sugerencia aquí es agregar también datos *dummy* a los *endpoints* de ```GET api/agents``` y ```GET api/agents/{agentId}```. 

Otra recomendación sería poner ```@GetMapping("/{agentId}")``` en la **línea 27** de este código en lugar de ```@GetMapping("/{id}")``` y ```@GetMapping("/metrics/{metricId}")``` en lugar de ```@GetMapping("/metrics/{id}")``` en la **línea 36**, con sus respectivas modificaciones en los parámetros que recibe la función en ```@PathVariable("id")``` a ```@PathVariable("metricId")``` o ```@PathVariable("agentId")``` dependiendo el caso.

2024-04-24 18:12 UTC, AntonioLaurance commented
Hay filtración de datos (tus credenciales de MySQL están reveladas) en el archivo **application.properties**.

2024-04-24 18:55 UTC, AntonioLaurance requested changes
Buenos cambios Fede, mi principal sugerencia sería arreglar los conflictos que se generaron por el cambio de nombre del **enum**, igual ya actualicé algunos comentarios anteriores comentando más recomendaciones.

2024-04-24 18:55 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/dtos/AlertDTO.java
Ya se cambio el tipo ```severity``` a ```AlertSeverity``` pero no se resolvieron todos los confilctos relacionados con el cambio de nombre, especialmente en la asignación de datos de tipo **enum**.

2024-04-24 18:55 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/AgentController.java
De este archivo creo que ya todo quedo, solamente hay que agregar datos *dummy* en la función ```getAgentById(@PathVariable("agentId") Long id)``` *endpoint* ```GET api/agents/{agentId}```.

2024-04-25 19:17 UTC, AntonioLaurance commented
No actualizado y resolver conflictos con ```main```.

2024-04-26 03:21 UTC, closed without merging