Se crearon Insight Endpoints
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #141
Opened 2024-05-27 07:04 UTC by MoyBadillo117

Se implementaron los siguientes endpoints:
/api/threshold-breach-inssights
/api/threshold-breach-inssights/type/{itemType}
/api/threshold-breach-inssights/status/{statusString} /api/threshold-breach-inssights/item/{connectItemId}

2024-05-27 17:22 UTC, Aram32mm requested changes

2024-05-27 17:22 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
te recomiendo solo hagas un endpoint con request params, en lugar de muchos con path params

2024-05-27 17:22 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/Metric/ThresholdBreachInsightDTO.java
documentar con swagger y eso no es parte de la carpeta metrica, Crea otra carpeta en el folder DTO llamado Insight o algo asi

2024-05-27 17:22 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/models/ThresholdBreachInsight.java
esto si estaba bien como estaba antes

2024-05-27 17:22 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/enums/ConnectItemType.java
por que hiciste otro enum igual al de ConnectMetricType

2024-05-27 17:22 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/enums/Status.java
esta fromString que es o que hace, la veo un poco fuera de lugar aqui en el enum, pero espero tu explicacion

2024-05-27 17:22 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/repositories/ThresholdBreachInsightRepository.java
bien

2024-05-27 17:22 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/services/ThresholdBreachInsightService.java
bien

2024-05-27 17:22 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/services/impl/ThresholdBreachInsightServiceImpl.java
ModelMapper

2024-05-27 21:10 UTC, MoyBadillo117 commented on src/main/java/com/springboot/connectmate/enums/ConnectItemType.java
No me di cuenta que el enum de metric era igual que el de insight

2024-05-27 21:10 UTC, MoyBadillo117 commented on src/main/java/com/springboot/connectmate/enums/Status.java
Es para que no se rompa si no recibe ningún dato que aparezca en el enum, es opcional, lo puedo eliminar.

2024-05-27 21:11 UTC, MoyBadillo117 commented on src/main/java/com/springboot/connectmate/services/impl/ThresholdBreachInsightServiceImpl.java
Por alguna razón no me funcionaba con modelMapper, lo resuelvo hoy

2024-05-27 21:12 UTC, MoyBadillo117 commented on src/main/java/com/springboot/connectmate/models/ThresholdBreachInsight.java
Como hice mi propio enum, tenia que usarlo en el modelo o se confundia a la hora de hacer el request

2024-05-27 22:19 UTC, AntonioLaurance requested changes
- [ ] Poner la **Pull Request** a la rama ```dev```.

2024-05-27 23:48 UTC, MoyBadillo117 commented
![Captura de pantalla 2024-05-27 174815](https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/126594825/38082f4e-3286-40c7-bd8f-eaad063acb77)

2024-05-28 00:22 UTC, Aram32mm requested changes
la pr la hiciste dev, hazla a main

2024-05-28 06:21 UTC, MoyBadillo117 commented
Patch de status ThresholdBreachInsight

![image](https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/126594825/44d8cc38-521f-42b6-88cd-16c59c5c83fc)

2024-05-28 19:44 UTC, abeejita requested changes

2024-05-28 19:44 UTC, abeejita commented on src/main/java/com/springboot/connectmate/enums/Status.java
En qué casos no tendría los datos definidos el enum?

2024-05-28 19:44 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
> +    @GetMapping
Ponle el @ApiResponse y el @Operation además del @GetMapping o @PatchMaapping a tus métodos del controlador

2024-05-28 23:03 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
> +    @GetMapping
como así JAJAJA

2024-05-29 02:14 UTC, AntonioLaurance reviewed
Buen trabajo Moy, sigue así!!
Puro **SQA**.

2024-05-29 04:45 UTC, closed without merging