endpoint user role
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #142
Opened 2024-05-27 22:19 UTC by fernando-tecm

2024-05-27 22:22 UTC, AntonioLaurance requested changes
- [ ] Hacer la **Pull Request** a la rama ```dev```.

2024-05-28 00:21 UTC, Aram32mm requested changes
Hola Fer, excelente, solo una cosa, necesito los security profile names, no los ids, creo que hay otra funcion que describe los roles y te da su name, checalo

2024-05-28 00:22 UTC, fernando-tecm commented
oki, lo agrego

2024-05-28 01:17 UTC, AntonioLaurance requested changes
- [ ] Hacer la **Pull Request** a la rama ```main```.

2024-05-28 19:48 UTC, abeejita commented
Dev está deprecated, sugiero hacer otra PR que solo tenga main y tus cambios

2024-05-28 19:48 UTC, abeejita requested changes
Dev está deprecated, sugiero hacer otra PR que solo tenga main y tus cambios

2024-05-28 20:07 UTC, fernando-tecm commented
pero el pr es para main

2024-05-28 23:04 UTC, closed without merging