Queue and Agent Metrics finished after some tears.
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #148
Opened 2024-05-28 03:24 UTC by abeejita

2024-05-28 23:52 UTC, AntonioLaurance requested changes
Muy buen código Abi, tus *endpoints* funcionan correctamente y el formato de tu JSON y DTO está excelente, mis únicas sugerencias aquí serían estilísticas y de tipos de datos.

¡Excelente trabajo, sigue así!

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/controllers/ConnectMetricController.java
> +            @RequestParam(name = "instanceArn") String instanceArn, @RequestParam(name = "agentId") String agentId){
Muy buena definición del controlador de tu **API**, mis sugerencias aquí serían:
- [ ] Poner un salto de línea entre decoradores ```@RequestParam``` de los argumentos de tu función ```getAgentMetrics```, esto con el propósito de estandarizar lo de la firma de las funciones con ```@RequestParam```.
- [ ] En el primer ```@RequestParam``` de tu función poner de nombre **instanceId** en lugar de **instanceArn** esto con el propósito de estandarizar el nombre del parámetro al insertarlo en el **JSON** entre diferentes **API** (quedando ```@RequestParam(name = "instanceId")```).
- [ ] En el primer parámetro de tu función cambiar su nombre por **instanceId** ya que la función de tu servicio toma un **instanceId** en lugar de un **instanceArn** pero al dar cualquier valor funciona igual.

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/AmazonConnectService.java
> +    ConnectAgentMetricDTO getAgentMetrics(String instanceArn, String agentId);
Muy buen código Abi, mi sugerencia aquí sería:
- [ ] Modificar el parámetro de tu función ```getAgentMetrics``` de ```String instanceArn``` por ```String instanceId```.

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectAgentMetricDTO.java
Buena documentación de tu **DTO** Abi, mis únicas sugerencias de estilo serían: 
- [ ] Poner de tipo de parámetro de tus atributos ```Double``` en lugar de ```double``` ya que ```double``` es un tipo de dato primitivo en **Java** y ```Double``` es un objeto y puede ser nulos a veces.
- [ ] ¿Qué dices Abi, también damos las unidades de las metricas en los *endpoints*?

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectQueueMetricDTO.java
Buena documentación de tu **DTO** Abi, mis únicas sugerencias de estilo serían: 
- [ ] Poner de tipo de parámetro de tus atributos ```Double``` en lugar de ```double``` ya que ```double``` es un tipo de dato primitivo en **Java** y ```Double``` es un objeto y puede ser nulos a veces.
- [ ] ¿Qué dices Abi, también damos las unidades de las metricas en los *endpoints*?

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
Muy buena definición de tu servicio para obtener las métricas.

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
> +    public ConnectQueueMetricDTO getQueueMetrics(String instanceArn, String queueId) {
- [ ] Cambiar el nombre del parámetro de la función ```String instanceArn``` por ```String instanceId```.

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
>          filters.add( new FilterV2()
- [ ] Eliminar el espacio entre el paréntesis ```(``` y el ```new``` del salto de línea).

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
> +                .withFilterValues(Collections.singletonList(queueId))
Buen detalle de hacer más paramétrica la función.

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
> +        ZonedDateTime now = ZonedDateTime.now(ZoneOffset.UTC);
Buen detalle de incluir la zona horaria.

2024-05-28 23:52 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
> +                .withResourceArn(instanceArn)
Veo que obtienes las métricas mediante ```GetMetricDataV2Request``` y que se usa el método ```.withResourceArn``` para filtrar por **instanceArn**, creo que si se le pasa un **instanceId** funciona igual pero no se que digan sobre la nomenclatura, ¿Qué dicen @abeejita y @Aram32mm, dejamos la nomenclatura del identificador de la instancia como **instanceId** o como **instanceArn**?

2024-05-28 23:54 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ConnectMetricController.java
>              @RequestParam(name = "instanceArn") String instanceArn,
Es que esta API de Connect necesita a fuerzas Instance ARN

2024-05-29 02:20 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ConnectMetricController.java
>              @RequestParam(name = "instanceArn") String instanceArn,
Ah ya te entendí, pero no sé, siento que va a estar un poco confuso que se llame Id pero que en realidad pida el arn

2024-05-29 02:30 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectQueueMetricDTO.java
mm no realmente, las unidades de las métricas nunca van a cambiar en front

2024-05-29 02:34 UTC, abeejita commented on src/main/java/com/springboot/connectmate/services/impl/AmazonConnectServiceImpl.java
> +                .withResourceArn(instanceArn)
personalmente me gustaría mantener los nombres de los parámetros de igual manera que la documentación de amazon connect para mejorar la mantenibilidad del código

2024-05-29 03:30 UTC, Aram32mm approved these changes

2024-05-29 03:30 UTC, merged