Patch de status ThresholdBreachInsight - Patch de Breaches Métrics
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #150
Opened 2024-05-28 17:39 UTC by JuliaPasten

2024-05-28 20:08 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ConnectMetricController.java
> -    private final AmazonConnectService amazonConnectService;
sí se necesita el AmazonConnectService. Si aparte necesitas el MetricService agrégalo, pero no borres el otro.

2024-05-28 20:23 UTC, abeejita requested changes

2024-05-28 20:23 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ConnectMetricController.java
> +    @PatchMapping("/{code}/thresholds")
pon el @ApiResponse y el @Operation a tu @PatchMapping

2024-05-28 20:23 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
> +    @PatchMapping("/{id}/status")
ponle @apiresponse y @operation a tu @patchmapping

2024-05-28 20:23 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/Update/UpdateStatusDTO.java
> +    private Status status;
documenta con @schema

2024-05-28 20:23 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/Update/UpdateThresholdMetricDTO.java
> +    private Double minimumThresholdValue;
documenta con @schema

2024-05-28 20:23 UTC, abeejita commented on src/main/java/com/springboot/connectmate/services/impl/MetricServiceImpl.java
> +        // Implementar lógica para obtener las métricas históricas
mmm esto está raro, la lógica de todos estos métodos ya estaba implementada

2024-05-28 20:25 UTC, abeejita commented
Como sugerencia general para tus próximos PRs, solo haz los nombres y las descripciones de tus commits en inglés

2024-05-28 23:10 UTC, abeejita requested changes

2024-05-28 23:10 UTC, abeejita commented on src/main/java/com/springboot/connectmate/services/impl/MetricServiceImpl.java
> +        return Collections.emptyList();
Estos métodos ya existían con lógica, si los vas a cambiar de lugar, cámbialos con todo y la lógica y evitar que se dupliquen en otros archivos

2024-05-29 03:33 UTC, AntonioLaurance requested changes
- [ ] Resolver conflictos con ```main```.

2024-05-29 05:15 UTC, JuliaPasten commented
comments ?

2024-05-29 06:05 UTC, Aram32mm commented
gracias Juls, ya junte tu codigo en el main!

2024-05-29 06:05 UTC, closed without merging