Email service ready, basic. no templates (No merge yet)
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #151
Opened 2024-05-28 18:48 UTC by zzentenoo

Holi! Estoy haciendo este PR para ir documentando los cambios que voy haciendo a los servicios de email y de SMS.

Este primer push es del servicio más básico para poder mandar un correo atraves del endpoint '/sendEmail'

Estaré implementando unas templates para los correos, Pablo y Caro compartieron un zip donde tienen mandar correos con AWS. En lo personal creo que está mejor si lo hacemos con springboot. Ustedes comentenme y cambio lo necesario.

Ahorita estaré trabajando en templates para los correos, después en implementar el proyecto de Caro y Pablo al proyecto, y después en conseguir la información necesaria (Alert name, recommendation y el link para pasar a un btn para redirigir a la alerta) para los correos y sms.

En el branch están las credenciales del correo que cree, luego las comparto en el grupo para usarlas mejor como parte de variables de entorno.

2024-05-28 19:32 UTC, AntonioLaurance commented
- [x] Yo en mi caso estaré trabajando en la migración del código de **Caro** y **Pablo** del SMS al código en general del proyecto.

2024-05-28 20:37 UTC, abeejita requested changes

2024-05-28 20:37 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/SMSController.java
> +    @PostMapping("/sendSms")
holi, por fis agrega un @apiResponse y @operation a tu @postmapping

2024-05-28 20:37 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/SMS/SMSRequestDTO.java
> +    private String message;
por fi agrega schema a cada atirbuto

2024-05-28 20:37 UTC, abeejita commented on src/main/java/com/springboot/connectmate/services/impl/EmailServiceImpl.java
> +            e.printStackTrace(); // Handle the exception based on your needs
default comment?

2024-05-28 22:04 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/dtos/SMS/SMSRequestDTO.java
> +    private String message;
Listo.

2024-05-29 04:04 UTC, zzentenoo commented
Holi! Solo para hacerles saber que la parte de correo debe de estar funcionando desde mi ultimo commit!

2024-05-29 04:11 UTC, AntonioLaurance commented
Igual voy a ver si lo puedo revertir a tu último *commit* Fede.

2024-05-29 04:25 UTC, AntonioLaurance commented
Creo que ya está de nuevo como lo dejaste al principio Fede.

2024-05-29 16:37 UTC, zzentenoo commented
Holi! Ando chambeando, no he metido mucha mano, todavia falta el servicio de SMS? Terminando de chanviar le puedo meter para que quede hoy en clase de Torres. Les parece?

2024-05-29 18:57 UTC, merged

2024-05-29 18:59 UTC, Aram32mm commented
excelente Fede, me apoyas con lo de los SMS

2024-05-29 18:59 UTC, Aram32mm commented
haz una nueva pr