Standard for Testing
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #152
Opened 2024-05-28 19:54 UTC by AntonioLaurance

2024-05-28 22:45 UTC, abeejita requested changes

2024-05-28 22:45 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectCurrentMetricDTO.java
> +    private String queueId;
poner @schema en atributos por fis

2024-05-28 22:45 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ConnectMetricDTO.java
> +    private String queueId;
poner @schema en todos los atributos

2024-05-29 01:46 UTC, Aram32mm requested changes
excelente richie, solo sube los DTOS porfa.  los tests ya estan en main

2024-05-29 04:30 UTC, AntonioLaurance commented
De acuerdo Aram!!

2024-05-29 04:41 UTC, AntonioLaurance commented
Ya está listo de nuevo solamente el **DTO** para integrarlo a ```main```.

2024-05-29 04:48 UTC, Aram32mm approved these changes

2024-05-29 04:48 UTC, merged