Insight creation
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #157
Opened 2024-05-28 23:17 UTC by Armando-Mandujano

Creación del endpoint para la creación de los registros de la tabla Threshold Breach Insight

2024-05-28 23:27 UTC, abeejita requested changes

2024-05-28 23:27 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/BedrockController.java
> +    @PostMapping("/ai/createInsight")
pueden poner @apiRequest y @operation además del @postmapping por favor

2024-05-28 23:27 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
> +            description = "Create the a   "
terminar la descripción por fis

2024-05-28 23:27 UTC, abeejita commented on src/main/java/com/springboot/connectmate/services/impl/BedrockServiceImpl.java
> +        ModelMapper modelMapper = new ModelMapper();
si no se usan, eliminar los comments

2024-05-28 23:27 UTC, abeejita commented on src/main/java/com/springboot/connectmate/services/impl/BedrockServiceImpl.java
> +
avoid unnecessary line breaks

2024-05-28 23:27 UTC, abeejita commented on src/main/java/com/springboot/connectmate/services/impl/BedrockServiceImpl.java
> +
avoid unnecessary line break

2024-05-28 23:27 UTC, abeejita commented on src/main/java/com/springboot/connectmate/services/impl/BedrockServiceImpl.java
> +                }else {
añadir espacio de llaves

2024-05-28 23:48 UTC, abeejita requested changes

2024-05-28 23:48 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/BedrockController.java
> +    @PostMapping("/ai/createInsight")
falta el content en apiResponse

2024-05-29 17:16 UTC, AntonioLaurance requested changes
- [x] Resolver conflictos con ```main```.

2024-05-29 18:55 UTC, Aram32mm requested changes
Excelente trabajo, un par de refinamientos, pero excelente. Hoy en clase les digo los proximos pasos, mientras corrijan los comments y prueben que este todo en orden

2024-05-29 18:55 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ThresholdBreachInsightDTO.java
este creo que tambien ya estaba antes jaja

2024-05-29 18:55 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/AmazonConnect/InsightDTO.java
mover todos los dtos a la carpeta Insights o crear una nueva, la carpeta AmazonConnect de por si ya tiene muchos archvios y las logicas no tienen nada que ver

2024-05-29 18:55 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/AmazonConnect/ThresholdBreachInsightDTO.java
esta con el nombre de ThresholdBreachInsightDetailsDTO, updatear imports

2024-05-29 18:55 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/services/impl/ThresholdBreachInsightServiceImpl.java
aqui no deberian de crear una metrica. Mas bien hagan un findById y pansele el code. Me preocupa que tenian errores de sintaxis, ya los correji, pero corran su branch para verificar que no haya algo mas. Mas que nada fue con el merge al main

2024-05-29 18:55 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/enums/ResponseField.java
esta raro que este file aparezca como verde creado. Si esta en el main

2024-05-29 19:32 UTC, AntonioLaurance requested changes
- [ ] Actualizar rama con ```main```.

2024-05-30 00:19 UTC, abeejita requested changes
muy bien, solo comments de limpieza de código

2024-05-30 00:19 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/BedrockController.java
> +            responseCode = "200",
en el apiResponse falta el content

2024-05-30 00:19 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
> +
avoid unnecessary line breaks

2024-05-30 00:19 UTC, abeejita commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
> +
avoid unnecessary line breaks

2024-05-30 00:20 UTC, Aram32mm approved these changes

2024-05-30 00:20 UTC, merged