Websocket Implemented
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #174
Opened 2024-05-30 12:37 UTC by AntonioLaurance

Se implementó un *websocket* del lado del servidor que manda mensajes cada vez que se crea un insight.

2024-05-30 14:09 UTC, AntonioLaurance commented
Agregue variables de entorno para la configuración del *WebSocker*:
- **SOCKET_PORT**: 8085
- **SOCKET_HOST**: localhost o la dirección IP de la nube donde está implementado el Backend.

2024-05-30 14:47 UTC, AntonioLaurance commented
Pruebas del funcionamiento del *websocket*: 
<img width="1392" alt="Screenshot 2024-05-30 at 8 47 42" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/74690107/08275b19-0fe4-4e0b-9b2e-c2baccb0c9dd">

2024-06-03 17:33 UTC, Aram32mm requested changes
Excelente Richie, todo se ve nítido. La única cosa que vería sería que adaptes este código a la lógica que se tiene de generar un Insight, como tal no esta expuesta mediante endpoint, entonces solo haz el switch y actualizate con los nuevos cambios

2024-06-03 17:33 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
Toda esta lógica, hazla en BedrockServiceImpl, función generateInsight, entre guardarlo en bd y todos los otros servicios complementarios, te deje un comment indicando donde. Esto no se expone via endpoint

2024-06-03 17:33 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/Message/MessageDTO.java
veo conveniente que mandes este dto en lugar de todo el insight, solo manda el nombre del insight y a quien pertenece y ya. todo el objecto insight tiene demasiados datos, que en realidad no se necesitan para una simple alerta cherry

2024-06-03 17:33 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/models/ThresholdBreachInsight.java
para que se usa este builder ?

2024-06-03 17:33 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/services/SocketService.java
solo ten una funcion sendMessage y manda el dto message que ya comente arriba :) o manda el generic dto

2024-06-03 17:33 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/socket/SocketModule.java
excelente

2024-06-03 17:33 UTC, Aram32mm commented on src/main/resources/application.properties
hardcodea las variables para no meter tanto ruido a los envs, por el momento unicamente

2024-06-03 17:42 UTC, AntonioLaurance commented on src/main/resources/application.properties
De acuerdo Aram!!

2024-06-03 18:04 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/models/ThresholdBreachInsight.java
Este decorador (@Builder) se usa para que se agregue otra forma de instanciar un objeto de este tipo, como por ejemplo los objetos de las credenciales de Amazon que las instanciaste con *builders*: 

```
 @Bean
    public AmazonConnect amazonConnectClient() {
        BasicAWSCredentials awsCredentials = new BasicAWSCredentials(accessKeyId, secretKey);
        return AmazonConnectClientBuilder.standard()
                .withRegion(Regions.fromName(region))
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                .build();
    }
```

En ese retorno de la función se crea una instancia con puros **Builders**.
Con un @Builder se podría instanciar de esta manera: 
```
ThresholdBreachInsight threshold = ThresholdBreachInsight.builder()
                .insightActions("Actions")
                .insightCategory(InsightPerformance.CRITICAL)
                .connectItemId("23821ad7d6e72")
                .insightSummary("Insight summary").build();
```
Igual voy escribiendo un comentario de lo que hace ese decorador.

2024-06-03 18:06 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/models/ThresholdBreachInsight.java
Solamente que los de amazon comienzan con "with" y el de nosotros es directamente el nombre del atributo.

2024-06-03 18:13 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/dtos/Message/MessageDTO.java
Eso si, igual creo que sería bueno por lo que Amazon y como está definido el objeto del modelo para la base de datos, ya que enviaba este mensaje a través del **WebSocket**:
```
{
    "id": 6,
    "metricCode": {
        "code": "OCCUPANCY",
        "minimumThresholdValue": null,
        "maximumThresholdValue": null,
        "targetValue": 10000
    },
    "connectItemId": "f0813607-af92-4a36-91e6-630ababb643c",
    "connectItemType": "QUEUE",
    "value": 892,
    "occurredAt": null,
    "status": "TO_DO",
    "insightName": "Contact Center Occupancy Below Threshold",
    "insightSummary": "The contact center's occupancy rate is currently at 81.62406272966678, which is below the threshold of 117.03421552356558. Therefore, the breach occurred.Here is a summary of the insight:The contact center's occupancy rate is below the threshold, indicating a breach.",
    "insightDescription": "The current value of the KPI, 81.62406272966678, is below the minimum threshold value of 77.38402268262857. Therefore, the breach occurred.The insight description is: The contact center's occupancy rate is below the threshold, indicating that there are fewer agents available to handle customer inquiries compared to the desired target. This can lead to longer wait times, increased customer frustration, and reduced customer satisfaction.",
    "insightActions": "The current value of the Occupancy KPI is 81.62406272966678, which is below the minimum threshold value of 77.38402268262857. Therefore, a threshold breach has occurred.Here are the recommended actions to address the threshold breach:1. Increase the number of agents available to handle incoming calls to reduce wait times and improve customer satisfaction.2. Implement a call routing system to ensure that calls are directed to the most qualified agents, reducing wait times and improving first-call",
    "insightCategory": "UNSATISFACTORY",
    "insightSeverity": "LOW",
    "insightRootCause": "The root cause of the threshold breach is that the current value of the Occupancy KPI is 81.62406272966678, which is less than the minimum threshold value of 77.38402268262857. Therefore, the breach occurred.Would you like to generate an insight to address this issue?",
    "insightImpact": "The overall performance impact of the threshold breach on the contact center's Occupancy KPI is minimal. Since the current value of 81.62406272966678 is still within the acceptable range of 77.38402268262857 to 146.0031777035005, there is no significant disruption or negative consequences associated with the breach.",
    "insightPrevention": "The current value of the Occupancy KPI is 81.62406272966678, which is below the minimum threshold value of 77.38402268262857. Therefore, a threshold breach has occurred. To prevent future threshold breaches, I recommend taking the following actions:1. Increase the number of agents available to handle customer inquiries.2. Implement a workload management system to ensure that agents are not overworked and can maintain a high level of service.3. Train agents on effective customer communication and problem"
}
```

Entonces voy a ver que atributos necesita tener el **DTO** para detonar la alerta.

2024-06-03 18:15 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/SocketService.java
De acuerdo Aram, ¿entonces borro la función de la **línea 13**?

2024-06-03 19:32 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/controllers/ThresholdBreachInsightController.java
Muchas gracias por los comentarios!!

2024-06-04 18:32 UTC, AntonioLaurance commented
Captura de pantalla de pruebas pasadas exitosamente:
<img width="1440" alt="Screenshot 2024-06-04 at 12 32 30" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/74690107/b968f7cd-149a-4a22-a89c-efa96b216547">

2024-06-04 22:42 UTC, Aram32mm approved these changes

2024-06-04 22:43 UTC, merged