Tests fede - Listear las instancias
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #178
Opened 2024-06-04 19:23 UTC by zzentenoo

<img width="1680" alt="Screenshot 2024-06-04 at 1 23 26 p m" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/66924428/73b8224b-8764-4652-a44c-5e42c95f4695">
<img width="1663" alt="Screenshot 2024-06-04 at 1 22 05 p m" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/66924428/7dfc2afb-4dda-49c6-8c98-479d289a175c">

si funcionaron

2024-06-04 22:27 UTC, Aram32mm requested changes
tu PR esta contaminado con lo de sockets, solo inclueyeme los tests

2024-06-04 23:36 UTC, AntonioLaurance requested changes
- [ ] Hay que conservar el archivo ```pom.xml```.

2024-06-05 00:04 UTC, AntonioLaurance requested changes
El ```pom.xml``` está vacío.

2024-06-05 00:28 UTC, abeejita requested changes
Bien, pequeños cambios

2024-06-05 00:29 UTC, abeejita commented
out of date con main ):

2024-06-05 00:48 UTC, AntonioLaurance requested changes
Excelente trabajo Fede, mis sugerencias aquí serían:
- [x] Corregir el error de la referencia circular en tus pruebas.
- [x] Misma sugerencia de Abi de nombrar tus métodos de prueba de acuerdo con la nomenclatura **given_when_then**.

2024-06-05 00:48 UTC, AntonioLaurance commented on src/test/java/com/springboot/connectmate/integration/AmazonConnectInstancesTests.java
> +    public void getInstance() throws Exception {
- [ ] Nombrar esté método siguiendo la nomenclatura de **given_when_then**.

2024-06-05 04:56 UTC, Aram32mm requested changes
metele el endline al final de todos los files y el pom la neta no se que por que se ve asi pero ponlo como main

2024-06-06 01:40 UTC, merged