Create ConnectUserControllerTests.java
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #179
Opened 2024-06-04 19:25 UTC by fernando-tecm

<img width="1320" alt="Captura de pantalla 2024-06-04 a la(s) 1 23 20 p m" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/105445226/d2694af4-ca0a-485a-9556-71170d5a3131">
<img width="1321" alt="Captura de pantalla 2024-06-04 a la(s) 1 23 37 p m" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/105445226/5cc2852c-86c7-4860-ae49-5571e3f05d99">
<img width="1358" alt="Captura de pantalla 2024-06-04 a la(s) 1 24 00 p m" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/105445226/9ad377e1-5dd3-4a1e-8dbf-dd9e7b52383a">

2024-06-04 22:37 UTC, Aram32mm requested changes
muy bien fer, haz json expects, no solo valides el status,  ejemplo seria 
```
response.andDo(print())
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.connectId", is("ed1ad50d-2ffc-44ad-a565-71f13ad991a5")))
                .andExpect(jsonPath("$.instanceId", is(registerUserFormDTO.getInstanceId())))
                .andExpect(jsonPath("$.username", is("aram_connectmate")))
                .andExpect(jsonPath("$.firstName", is("José Aram")))
                .andExpect(jsonPath("$.lastName", is("Méndez Gómez")))
                .andExpect(jsonPath("$.email", is(registerUserFormDTO.getEmail())))
                .andExpect(jsonPath("$.secondaryEmail", is("jose.aram.mendez@gmail.com")))
                .andExpect(jsonPath("$.mobile", is("+523525231067")))
                .andDo(print());
```

2024-06-04 22:38 UTC, Aram32mm commented
tambien actualiza tu branch

2024-06-04 23:38 UTC, AntonioLaurance requested changes
- [ ] Actualizar rama con ```main```.

Dentro de los demás aparte de lo que menciono Aram, veo las pruebas bien.

2024-06-05 00:31 UTC, abeejita requested changes
Bien, solo un comentario de limpieza + los de richie y aram

2024-06-05 00:31 UTC, abeejita commented on src/test/java/com/springboot/connectmate/integration/ConnectUserControllerTests.java
> +        ResultActions response = mockMvc.perform(get("/api/amazon-connect/instances/{instanceId}/users/{userId}/description", instanceId,userId)
espacio antes de userId

2024-06-05 00:49 UTC, AntonioLaurance commented
- [ ] Actualizar rama con ```main```.

2024-06-06 17:21 UTC, closed without merging