Agregue MetricsController y RecommendationController
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #3
Opened 2024-04-05 18:49 UTC by JuliaPasten

2024-04-05 22:14 UTC, abeejita approved these changes
oki

2024-04-05 23:18 UTC, AntonioLaurance reviewed
Esta todo bien, solamente recomendaría definir una clase por archivo, **RecomendationController.java** define 2 clases, pienso que la clase de representación de recomendación interna debería de ir en otro archivo. ¿Qué dicen?

2024-04-05 23:18 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/RecommendationController.java
Creo que la clase de interna para representar una recomendación iría en otro archivo dentro de la carpeta Models.

2024-04-05 23:18 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/RecommendationController.java
¿Qué dicen acerca de esto?

2024-04-05 23:43 UTC, Aram32mm reviewed
Hola juls, muy bien solo hay que refinar algunas cosas:

1. En los controllers no uses mapas ni clases embebidas, justamente para eso son los DTOS, para manipular los datos en un esquema. Crea los DTOs, importalos y populalos. (IMPORTANTE: en tu DTO usa Lombok con @Data para que te haga todos los metodos de la clase y no tengas que escribir una sola linea de codigo)
2. Documenta los endpoints y los DTOs. La clase controller con decorador @Tag, los metodos del controller con decorador @Operation y @ApiResponse, y los DTOs con decorador @Schema. Todo esto es de Swagger pero trata de hacerlo lo mejor posible y en ingles todo, al final nos va a permitir saber exactamente que hace cada funcion

Apoyate mucho del SupervisorController y el SupervisorDTO. Esas clases estan tal cuál hechas cómo te comento, incluso puedes hacer copy paste y adaptar la información correspondiente. Cualquier duda por WA

2024-04-05 23:46 UTC, Aram32mm commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/RecommendationController.java
Si, es lo que le comente, esto debería ser un DTO, estando en la carpeta dtos.

2024-04-05 23:56 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/RecommendationController.java
Es cierto debería estar en la carpeta de **dtos** y no en la de **models** como comenté arriba.

2024-04-10 00:23 UTC, AntonioLaurance approved these changes
Hasta ahora todo el código bien, todo funcional y las clases bien definidas con nombres coherentes para el miércoles, en el futuro sugiero hacer lo de los comentarios anteriores pero por ahora todo bien. Excelente trabajo Moi 😃!!

2024-04-10 03:15 UTC, AntonioLaurance requested changes
Excelente trabajo Julia, solamente faltaría incluir el **Package** en los archivos de los **Controllers** ya que sin la linea de **Package** los endpoints no pueden funcionar, de allí en fuera todo bien para el miércoles.

2024-04-16 06:10 UTC, AntonioLaurance commented
Nueva fecha de entrega: ```Lunes 22 de abril del 2024```

2024-04-21 19:19 UTC, Aram32mm requested changes
por que hay varios files con terminación en 2 ?

2024-04-23 16:51 UTC, AntonioLaurance commented
Resolver conflictos con main.

2024-04-25 19:19 UTC, AntonioLaurance commented
¿@JuliaPasten puedo cerrar esta **Pull Request** ya que hace referencia a la rama anterior?

2024-04-26 03:21 UTC, closed without merging