Modified Dockerfile and properties.
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #68
Opened 2024-04-18 01:48 UTC by abeejita

2024-04-18 06:22 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/resources/application.properties
Gracias por los cambios en este archivo Abi, que creo que con mi pull request se desarregló.

2024-04-18 06:35 UTC, AntonioLaurance requested changes
Buenas modificaciones al **Dockerfile** mi única recomendación y cambios requeridos son agregar comentarios al **Dockerfile**, ¡muy bien @abeejita!

2024-04-18 06:35 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/Dockerfile
Muy buenas modificaciones al **Dockerfile** @abeejita conforme a lo que mostró profesor, mis únicas notas aquí son escribir comentarios en inglés sobre lo que hace cada línea y quitar la línea 9 de ```WORKDIR /app``` ya que puede ser redundante. 

De allí en fuera todo bien :)

2024-04-18 17:23 UTC, Aram32mm approved these changes

2024-04-21 02:32 UTC, abeejita commented on springboot-connectmate-rest-api/Dockerfile
Listo @AntonioLaurance , gracias por los comentarios. Ya quedaron resueltos :)

2024-04-21 02:38 UTC, AntonioLaurance approved these changes
Buen trabajo @abeejita!!, por mi parte ya lo veo todo bien listo para ser integrado a la ```main```.

2024-04-21 02:39 UTC, merged