Created endpoint to post insights.
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #74
Opened 2024-04-22 04:31 UTC by CaroGlez15

2024-04-22 06:52 UTC, AntonioLaurance requested changes
Buen trabajo Caro!!, la API es completamente funcional y el código está bien documentado, mis únicos cambios sugeridos son lo del estatus **HTTP** que devuelve como respuesta la API.

2024-04-22 06:52 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/InsightController.java
Buena adición de *endpoint* ```POST /api/insight``` @CaroGlez15, sobre todo porque no está documentado en el google docs de *endpoints* y es un servicio que nos podría servir en el futuro, por esto muchas gracias, aquí mis sugerencias:
- [ ]  Que la función perteneciente al *endpoint* no regrese ningún texto, en este caso actualmente regresa **"Insight created successfully"**.
- [ ]  Que el *endpoint* retorne al cliente el estatus ```201 (Created)``` de ```HTTP``` y no el estatus ```200 (OK)```, así podremos comprobar con solamente el estatus si la solicitud de ```PUSH``` para agregar un registro fue procesada exitosamente por el servidor y como resultado la base de datos tiene un nuevo registro.
- [ ] En las **líneas 93 a 96** del código todo el decorador de ```@ApiResponse``` sugiero que mejor iría en el arreglo ```values``` dentro del decorador ```@ApiResponses``` ubicado en las **líneas 76 a 87** del presente código ya que así **Swagger** podría documentar todos los códigos de respuesta HTTP en caso de la solicitud sea exitosa o no, en este caso como sugerencia opcional sugiero agregar los estatus:
                 - ```401 (Unauthorized)``` (para usuarios no autenticados por la aplicación)
                 - ```403 (Forbidden)``` (para usuarios no autorizados a utilizar esta API, pero si autentificados)
 ¿Qué opinas acerca de esto Caro (@CaroGlez15) te gustaría o no implementarlo?
- [ ] Hay que quitar el ```@ApiResponse``` con código ```200 (OK)``` del arreglo de ```values``` de ```@ApiResponses``` (líneas **77 a 82** del código) ya que en las API's de ```PUSH``` generalmente no se retorna este estatus y ese estatus generalmente se retorna con ```GET```, ```PUT``` o ```PATHCH``` pero no con ```PUSH``` o ```DELETE```.

De allí en fuera todo bien, haznos saber tu opinion acerca de esto.
Buenas noches.

2024-04-23 14:39 UTC, Aram32mm commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/InsightController.java
Hola Richie, si quieres havcer esto? En todos los demás controllers está solo con operation y response. De hecho le dije a Pablo que lo quitara de su PR jaja, pero si sientes que enriquece el código adelante. Yo lo digo por que la mayor parte esta estandarizado de esa manera y considero que le agrega mucho ruido al código.



En las líneas 93 a 96 del código todo el decorador de @ApiResponse sugiero que mejor iría en el arreglo values dentro del decorador @ApiResponses ubicado en las líneas 76 a 87 del presente código ya que así Swagger podría documentar todos los códigos de respuesta HTTP en caso de la solicitud sea exitosa o no, en este caso como sugerencia opcional sugiero agregar los estatus:
- 401 (Unauthorized) (para usuarios no autenticados por la aplicación)
- 403 (Forbidden) (para usuarios no autorizados a utilizar esta API, pero si autentificados)
¿Qué opinas acerca de esto Caro (@CaroGlez15) te gustaría o no implementarlo?

2024-04-23 16:49 UTC, AntonioLaurance commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/InsightController.java
Ese es un buen punto Aram, de solo dejar ```@ApiResponse``` y quitar lo de ```@ApiResponses``` para lo de estandarizar con el resto del código, por mi está bien hacerlo así, va me gusta la idea. Entonces me tocará hacer eso con mis *endpoints* ya que puse ```@ApiResponses```, muchas gracias por tu comentarios. 

En este caso voy a actualizar mi comentario anterior.

2024-04-24 22:30 UTC, abeejita commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/InsightController.java
mismos comments que richie y listo :))

2024-04-25 19:16 UTC, AntonioLaurance commented
Falta actualizar la rama con ```main```.

2024-04-26 03:21 UTC, closed without merging