Luis armando mandujano chávez a01655899
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #75
Opened 2024-04-23 00:03 UTC by Armando-Mandujano

Agregué los endpoints 5 y 6

2024-04-23 01:47 UTC, abeejita commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/controllers/AgentsMetricsController.java
> +
evitar espacios de más

2024-04-23 01:53 UTC, abeejita commented
Estas no son las métricas que vamos a utilizar (Revisar SRS). Limpiar el DTO para que solamente se usen los KPIs que mostraremos.

2024-04-23 01:54 UTC, abeejita commented
Renombrar los DTOs para el tipo de elemento que necesitará esos datos (Por ejemplo, MetricDTO, AgentDTO, AlertDTO, etc.)

2024-04-23 01:55 UTC, abeejita commented
Los endpoints regresan tal cual el DTO en vez de un response entity con el DTO

2024-04-23 01:57 UTC, abeejita commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/dtos/AgentDetailsDTO.java
> +    public List<EP6_DTO> getKPIs() {
Trata de utilizar los decorators que te generan automaticamente los getters y setters. Puedes ver los ejemplos de alert o supervisor para guiarte.

2024-04-23 01:58 UTC, abeejita commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/dtos/EP5_DTO.java
> +    private int totalCalls;
Igual, usar decorators y modificar las métricas

2024-04-23 02:00 UTC, abeejita commented on springboot-connectmate-rest-api/src/main/java/com/springboot/connectmate/dtos/EP6_DTO.java
> +
Igual, usar decorator para getters y setters

2024-04-24 06:11 UTC, Aram32mm approved these changes

2024-04-24 14:45 UTC, AntonioLaurance requested changes
Buen código Armando, mis sugerencias son como dijo Abi sobre limpiar los DTO's, comentarios en inglés más algunas que puse en archivos específicos. 

De allí en fuera todo bien con la **Pull Request**.

2024-04-25 19:16 UTC, AntonioLaurance commented
No actualizado.

2024-04-26 03:21 UTC, closed without merging