Julia pasten da silva a01660665
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #90
Opened 2024-04-28 00:51 UTC by JuliaPasten

No he podido correr el proyecto al parecer es por un warning pero no consegui resolverlo, espero alguien pueda ayudarme. Igual aprobación de mi dto y end point api/threshold-breaches GET ALL ALERTS (IN THE DB ARE LIKE THRESHOLD BREACHES)

<img width="1440" alt="image" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/113377269/d512a1e2-0560-4cff-a4ea-6d7f14eda327">
<img width="1440" alt="image" src="https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/113377269/a05b1b86-d437-4bcc-a766-c80729420d02">

2024-04-28 02:26 UTC, Aram32mm commented on springboot-connectmate-rest-api/src/main/java/com/tuapp/modelo/Recommendation.java
que es este archivo ? y por que está fuera del folder ? veo que es una clase recomendacion, para que está?

2024-04-28 02:27 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/RecommendationDTO.java
Ya no tenemos recomendaciones, solo insights. Este DTO es inválido.

2024-04-28 02:30 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/RecommendationController.java
por que hay un recommendation controller?

2024-04-28 02:31 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/MetricsController.java
Por que hay un metrics controller?

2024-04-28 02:31 UTC, AntonioLaurance requested changes
Estuve revisando tu código y podría decir que te falta definir la clase ```AlertNotFoundException```, además de que faltan definir los métodos en la interfaz de ```AlertService``` para que se pueda conectar la clase de implementación de servicios de ```AlertServiceImpl```.

Hasta ahora eso fue lo que ví por lo que falló el código. En caso de cualquier duda @JuliaPasten puedes consultarnos por este medio o por el grupo de **Whatsapp**.

2024-04-28 02:32 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/AlertController.java
no entiendo ppor que se esta borrando mucho codigo ya hecho y se esta volviendo a poner

2024-04-28 02:33 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/dtos/Alert/AlertDTO.java
DTO sin documentaci'on y todo ese codigo de getters y setters te lo pudiste ahorrar con @data

2024-04-28 04:52 UTC, abeejita commented
Antes de hacer más revisiones es necesario que tu branch esté actualizada con la versión más reciente de main para que tengas los archivos y estructura correcta. Eso puede que resuelva algunos de tus problemas. Después, creo que el video de @Aram32mm puede a ayudarte a hacer tu endpoint de una amnera un poquito más fácil. Si sigues teniendo problemas después de esas dos cosas y de corregir los comentarios de richie y aram, mándanos mensajito con confianza! :))

2024-04-28 04:53 UTC, abeejita requested changes
changes requested

2024-04-28 08:24 UTC, Aram32mm requested changes
Hola juls, acabo de diseñar el DTO, ya lo pushee e hice un endpoint para que te guiaras. Toma como referencia todos los cambios que acabo de pushear. Hice el endpoint get by id, tu tinees que hacer el get all

2024-04-29 18:32 UTC, JuliaPasten commented
Ayer no estaba en mi casa , hoy le doy

2024-04-30 02:10 UTC, JuliaPasten commented
Chequen mi ultimo commit plssss

2024-04-30 02:36 UTC, closed without merging