api/users PATCH
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #93
Opened 2024-04-28 18:24 UTC by A01662420

2024-04-28 20:26 UTC, Aram32mm requested changes
Tu branch está desactualizada, hay muchos conflictos con el main. Tu endpoint cómo tal ya está hecho, solo tienes que crear el UserInfoDTO que no devuelva datos sensibles como contraseñas. una vez creado devuelve este dto en lugar del userdto.

2024-04-28 21:21 UTC, abeejita commented on .gitignore
> +<<<<<<< Updated upstream
Hay que corregir este merge, se quedaron los comentarios de git en el .gitignore

2024-04-28 21:23 UTC, abeejita commented on .gitignore
> +<<<<<<< Updated upstream
En general, actualiza tu branch con la versión más reciente de main para hacer el mergeo de tu PR. Después de eso podemos revisar los archivos :=)

2024-04-28 21:24 UTC, abeejita commented
Si puedes también adjunta foto de tu endpoint funcionando en postman/restman/navegador en el PR por fi

2024-04-28 21:24 UTC, abeejita requested changes
changhes requested

2024-04-29 15:34 UTC, AntonioLaurance requested changes
Actualizar ```branch``` y resolver conflictos con ```main```.

2024-04-29 23:57 UTC, closed without merging