Se creó el endpoint
Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend pull request #97
Opened 2024-04-29 07:41 UTC by MoyBadillo117

Se creó el endpoint GET ALL INSIGHTS FROM ONE AGENT
![Captura de pantalla 2024-04-29 013247](https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/126594825/4c7e7743-43ca-465b-955d-661920b4cd7f)
![image](https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/126594825/a63d7343-c740-447a-b4b6-813e29a26b88)

2024-04-29 15:28 UTC, Aram32mm requested changes
Excelente acercamiento Moy, branch actualizada, y en general tienes una buena idea de que estás haciendo. Solo arregla esos detalles

2024-04-29 15:28 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/controllers/InsightController.java
bien

2024-04-29 15:28 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/repositories/InsightRepository.java
Moy, buen acercamiento. 1 cosas a tener en cuenta, usa RAW SQL queries en lugar de JPQL queries, los queries crudos de sql son más eficientes y para migrarlos cómo stored procedures es mucho más facil, solo es copy paste. La unica diferencia es que en tu query actual estas usando los nombres de las entidades de JPA, solo adaptalo para que use las tablas tal cual nombradas en base de datos, para mayor referencia de querys sql raw, este es uno que use para templates : @Query(value = "SELECT t.* FROM threshold_breaches tb " +
            "INNER JOIN metrics m ON tb.metric_id = m.id " +
            "INNER JOIN templates t ON m.id = t.metric_id " +
            "WHERE tb.id = :breachId", nativeQuery = true)
    Template findTemplateByBreachIdSQL(@Param("breachId") Long breachId);

2024-04-29 15:28 UTC, Aram32mm commented on src/main/java/com/springboot/connectmate/services/impl/InsightServiceImpl.java
usa model mapper para convertir modelos a dtos

2024-04-29 23:47 UTC, AntonioLaurance requested changes
¡Buen trabajo Moi!, hemos visto que en tus **JSON** de los *endpoints* hay muchos atributos nulos (```null```), esto debido a que en los *endpoints* solamente estas obteniendo los atributos de una sola tabla y los datos que necesita tu **DTO** no están en una sola tabla de la base de datos, para esto sugerimos utilizar **Stored Procedures** para obtener los datos de tu API.

En caso de tener dudas con estos **Stored Procedures**, te sugiero contactar con nuestra experta en estos procedimientos @abeejita.

2024-04-30 02:13 UTC, abeejita commented
En vez de stored procedures mejor usar **vistas**.

2024-04-30 07:06 UTC, MoyBadillo117 commented
> vistas

Hola, los nulls deben ser causa porque en los dtos de insights hay templates que como tal no se que hagan. (no los agregué yo)

2024-04-30 07:32 UTC, MoyBadillo117 commented
![Captura de pantalla 2024-04-30 011847](https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/126594825/c450537c-0677-49fa-8f41-24363ee73055)

2024-04-30 15:42 UTC, Aram32mm requested changes
Noooo, no se los quites padrino, asi es la logica.

2024-04-30 15:43 UTC, Aram32mm commented
si quieres hoy en clase te digo como sacar el template data

2024-04-30 16:02 UTC, AntonioLaurance requested changes
¡Buen código **Moises Badillo**!, mis únicas notas aquí son sobre incluir la documentación en **Swagger** con los decoradores ```@ApiResponse``` y ```@Operation``` además de incluir la estructura del **JSON** como estaba antes modificando un poco tu *query* para que no te dé valores ```null``` en algunos de los campos como te retornaba. 

Fuera de eso todo bien, excelente trabajo.

2024-04-30 18:38 UTC, abeejita commented on src/main/java/com/springboot/connectmate/dtos/Insight/InsightDTO.java
X2

2024-04-30 18:39 UTC, abeejita commented on src/main/java/com/springboot/connectmate/repositories/InsightRepository.java
> +    @Query(value = "SELECT i.* FROM insights i " +
aquí es donde puedes implementar las vistas moy

2024-04-30 18:41 UTC, abeejita requested changes
puse poquitos comments, en general de acuerdo con aram y richie

2024-05-01 05:21 UTC, MoyBadillo117 commented
![image](https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/126594825/873ba310-cc55-4051-a320-ca029a91012b)
![Captura de pantalla 2024-04-30 231730](https://github.com/Tec-de-Monterrey-Capstone-Project-2024/SpringBoot_Backend/assets/126594825/88cac03a-2f5b-457a-bb54-11d4d093b63e)

2024-05-01 05:31 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/controllers/InsightController.java
¡Buenos cambios **Moises Badillo**!, veo que ya documentaste tu *endpoint* con los decoradores de **Swagger**.

2024-05-01 09:48 UTC, MoyBadillo117 commented on src/main/java/com/springboot/connectmate/controllers/InsightController.java
Hola Richie, vi que solicitaste un cambio. ¿Qué debo cambiar ? ¡Saludos!

2024-05-01 17:20 UTC, Aram32mm requested changes
por q cambiaste la ultima funcion de getqueueinsights

2024-05-01 19:34 UTC, AntonioLaurance approved these changes
¡Excelente trabajo Moy!, uno de los mejores **Pull Request** que he visto, tu *endpoint* funciona correctamente y ya no muestra ```null``` en algunos atributos (me gusto sobre todo la forma en que usaste ese *mapper*), tengo algunas sugerencias solamente de saltos de línea y redacción, pero estas pueden ser abordadas después ya que son mínimas.

¡Muchas felicidades!

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/InsightServiceImpl.java
> +import com.springboot.connectmate.repositories.UserRepository;
- [ ] Eliminar este ```import``` de **UserRepository** no usado.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/InsightServiceImpl.java
> +
Nada más una sugerencia de estética aquí es:
- [ ] Eliminar los saltos de línea de la **línea 45** a la **línea 48** con el propósito de estandarizar los saltos de línea que separan funciones.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/InsightServiceImpl.java
> +
Sugerencia de eliminar este salto de línea.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/impl/InsightServiceImpl.java
Muy ingeniosa forma de usar los *mappers* @MoyBadillo117  te lo reconozco y me alegra ver que alguien uso *mapper* doble.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/InsightService.java
> +
Sugerencia de quitar este salto de línea para estandarizar.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/InsightService.java
> +
Sugerencia de quitar este salto de línea para estandarizar.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/InsightService.java
> +
Sugerencia de quitar este salto de línea para estandarizar.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/InsightService.java
> +
Sugerencia de quitar este salto de línea para estandarizar.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/services/InsightService.java
Buen prototipo de función en la interfaz de **InsightService**.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/controllers/InsightController.java
Veo de nuevo todo este código bien, solamente tendría una sugerencia de redacción en la descripción del **Swagger** que te puse en otro comentario.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/repositories/InsightRepository.java
> +    @Query(value = "SELECT i.* FROM insights i " +
Justo, al igual que Abi aquí recomendaría implementar una **vista** en lugar del *query* completo.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/repositories/InsightRepository.java
> +
Sugerencia de quitar este salto de línea.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/repositories/InsightRepository.java
Todo bien Moy veo que ya quitaste los  ```import``` no usados y tu método funciona de maravilla.

2024-05-01 19:34 UTC, AntonioLaurance commented on src/main/java/com/springboot/connectmate/dtos/Insight/InsightDTO.java
Mi única sugerencia para este archivo es quitar este salto de línea, de allí en fuera todo está excelente con este **DTO**.

2024-05-01 20:06 UTC, abeejita requested changes
En general bien, creo que solo haría falta implementar algunos comments de limpieza / buenas prácticas de Richie e implementar la vista

2024-05-02 00:26 UTC, AntonioLaurance commented
Como comentario extra a lo de Abi, la nomenclatura definida para las vistas es:
```v_<nombre de la vista>``` 

Donde todo se debe escribir en ```snake_case```, **<nombre de la vista>** se sustituye por el nombre de la vista que debe ser en inglés y la vista no debe llevar verbos en su nombre como **get**, **recover** ni cosas así,

2024-05-02 02:47 UTC, Aram32mm approved these changes

2024-05-02 02:51 UTC, Aram32mm requested changes
Ya nunca me contestaste, por que cambiaste las ultimas lineas getQueueInsights

2024-05-02 02:55 UTC, AntonioLaurance commented
Resolver conflictos con ```main``` y actualizar rama.

2024-05-02 02:55 UTC, MoyBadillo117 commented
> Ya nunca me contestaste, por que cambiaste las ultimas lineas getQueueInsights

AYUDA

2024-05-02 02:58 UTC, Aram32mm approved these changes

2024-05-02 03:00 UTC, abeejita commented
a la cuenta de tres lloro porque no hay vistas

2024-05-02 03:01 UTC, MoyBadillo117 commented
> a la cuenta de tres lloro porque no hay vistas

Esperaaa es que no se como hacer eso jajaja, dejame meto vistas

2024-05-02 03:07 UTC, abeejita commented
nada más haz un CREATE VIEW "v_nombre_de_la_vista" AS
*AQUI TODO EL QUERY QUE TIENES*;

Y cuando hagas el @Query ya nada más llamas el 
SELECT * FROM v_nombre_de_la_vista

y donde está el @OVERRIDE quitas el @TRANSACTION

2024-05-02 03:07 UTC, Aram32mm commented
raw queries jpa > views. Si el dia de mañana quieren migrar a AWS RDS y tumbamos la GCP Mysql que tenemos, vamos a tener que rehacerlas, conectandote a base de datos, create view blah blah blah jajaja si ya defines de una tu query ya se queda ahi y no tienes que rehacer ni configurar nada, podriamos decir que en cierto sentido es una vista solo que manejada por JPA 😳👉🏻👈🏻

2024-05-02 03:14 UTC, abeejita commented
pero también es por la complejidad de los queries y por privacidad, así prácticamente estamos exponiendo al repo la estructura de nuestra BD 😞

2024-05-02 03:16 UTC, abeejita commented
de todos modos de entre como está ahorita con Stored Procedures a Vistas, convienen vistas

2024-05-02 03:32 UTC, Aram32mm commented
hmm pues de la privacidad no te preocupes jaja pues esa es la idea que nuestro back se haga como un sistema acoplado a la bd, por eso tenemos todos nuestros modelos definidos dentro junto con la lógica de negocio jeje De lo otro si estoy completamente de acuerdo, todos los stored procedures deben ser vistas. Pero los querys ?🤔 Esos considero que hay que dejarlos así y mientras más madure nuestro sistema y tengamos nuestros patrónes de acceso mejor definidos y procedimientos detectados podemos  hacer los seeders de sql con vistas e incluso stored procedures

2024-05-02 03:58 UTC, MoyBadillo117 commented
Ya quedó la view, espero @abeejita ya me pueda perdonar 😔

2024-05-02 04:03 UTC, abeejita commented on src/main/java/com/springboot/connectmate/repositories/InsightRepository.java
> +    @Query(value = "SELECT * FROM v_get_agent_insights WHERE user_id = :agentId", nativeQuery = true)
feli

2024-05-02 04:05 UTC, abeejita approved these changes

2024-05-02 04:07 UTC, merged